/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if cstdint is available for CoinUtils */
#define COINUTILS_HAS_CSTDINT 1

/* Define to 64bit integer type */
#define COIN_INT64_T int64_t

/* Define to integer type capturing pointer */
#define COIN_INTPTR_T intptr_t

/* Define to 64bit unsigned integer type */
#define COIN_UINT64_T int64_t

/* Define to 1 if you have the <cfloat> header file. */
#define HAVE_CFLOAT 1

/* Define to 1 if you have the <cmath> header file. */
#define HAVE_CMATH 1
