/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Version number of project */
#define CLP_VERSION "1.17.3"

/* Major Version number of project */
#define CLP_VERSION_MAJOR 1

/* Minor Version number of project */
#define CLP_VERSION_MINOR 17

/* Release Version number of project */
#define CLP_VERSION_RELEASE 3

/* Define to 1 if the AMD package is available */
/* #undef COIN_HAS_AMD */

/* Define to 1 if the CHOLMOD package is available */
/* #undef COIN_HAS_CHOLMOD */

/* Define to 1 if you have the <cmath> header file. */
#define HAVE_CMATH 1
