/* src/config_clp.h.  Generated by configure.  */
/* src/config_clp.h.in.  */

/* Version number of project */
#define CLP_VERSION "1.17.3"

/* Major Version number of project */
#define CLP_VERSION_MAJOR 1

/* Minor Version number of project */
#define CLP_VERSION_MINOR 17

/* Release Version number of project */
#define CLP_VERSION_RELEASE 3
